server {
    listen 80;
    server_name localhost;

    # Proxy untuk Backend API
    location /api {
        proxy_pass http://sal_lib_backend_dev:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy untuk Frontend (Vite Dev Server)
    location / {
        proxy_pass http://sal_lib_frontend_dev:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
